# Generated by Django 4.2.4 on 2023-08-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="opener",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
