# Generated by Django 4.2.4 on 2023-08-25 17:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0002_alter_concert_opener"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="country",
            field=django_countries.fields.CountryField(default="US", max_length=2),
        ),
    ]
