# Generated by Django 4.2.4 on 2023-08-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0003_alter_venue_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
