# Generated by Django 4.2.4 on 2023-08-25 20:41

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0005_artist_first_last_name_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="artist",
            name="first_last_name_unique",
        ),
        migrations.AddConstraint(
            model_name="artist",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="artist_name_unique"
            ),
        ),
    ]
