# Generated by Django 4.2.4 on 2023-08-26 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0006_remove_artist_first_last_name_unique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="venue", to="concerts.venue"
            ),
        ),
    ]
