# Generated by Django 4.2.4 on 2023-08-31 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("concerts", "0009_alter_concert_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="concert",
            name="attendees",
            field=models.ManyToManyField(related_name="concerts", to=settings.AUTH_USER_MODEL),
        ),
    ]
