# Generated by Django 4.2.4 on 2023-09-28 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0010_concert_attendees"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="venue",
            unique_together={("name", "city")},
        ),
    ]
