# Generated by Django 4.2.4 on 2023-09-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0011_alter_venue_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name="concert",
            name="opener",
        ),
        migrations.AddField(
            model_name="concert",
            name="opener",
            field=models.ManyToManyField(blank=True, related_name="opener_concerts", to="concerts.artist"),
        ),
    ]
