# Generated by Django 4.2.4 on 2023-10-01 03:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0012_alter_artist_name_remove_concert_opener_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concert",
            name="festival",
        ),
    ]
