# Generated by Django 4.2.4 on 2023-10-04 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0014_concertreview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concertreview",
            options={"verbose_name_plural": "Concert Reviews"},
        ),
        migrations.AddField(
            model_name="artist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="concert",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venue",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
