# Generated by Django 4.2.4 on 2023-10-06 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0015_alter_concertreview_options_artist_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concertreview",
            name="concert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="concerts.concert"
            ),
        ),
    ]
