# Generated by Django 4.2.4 on 2023-10-10 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0016_alter_concertreview_concert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
