# Generated by Django 4.2.4 on 2023-10-20 03:17

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0017_alter_concert_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="state",
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
    ]
