# Generated by Django 4.2.4 on 2023-10-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0020_remove_artist_artist_name_unique_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="artist",
            name="artist_name_unique",
        ),
        migrations.AddConstraint(
            model_name="artist",
            constraint=models.UniqueConstraint(models.F("musicbrainz_id"), name="artist_mbid_unique"),
        ),
    ]
