REAL_ARTIST_NAMES = [
    "The Beatles",
    "Madonna",
    "Led Zeppelin",
    "Michael Jackson",
    "Queen",
    "Adele",
    "Taylor Swift",
    "Beyoncé",
    "Drake",
    "Rihanna",
    "Ed Sheeran",
    "Coldplay",
    "Elton John",
    "Eve 6",
    "The Rolling Stones",
    "Arctic Monkeys",
    "Radiohead",
    "Nirvana",
    "Oasis",
    "Blur",
    "Pulp",
    "Muse",
    "The Kinks",
    "The Zombies",
    "The Cranberries",
    "The Chainsmokers",
    "The Weeknd",
    "Two Door Cinema Club",
    "Florence + the Machine",
    "The National",
    "Interpol",
    "Editors",
    "Passenger",
    "The Passengers",
    "Tame Impala",
    "Wolf Alice",
    "Bat For Lashes",
    "Beach House",
    "Beach Fossils",
    "Parcels",
    "The Strokes",
    "Temples",
    "Alt-J",
    "Chvrches",
    "The Church",
    "Fleet Foxes",
    "Foals",
    "The War on Drugs",
    "Warpaint",
    "Sunflower Bean",
]
