name: Behave Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and run containers using docker-compose
      run: |
        docker-compose up -d

    - name: Run Behave tests
      run: |
        docker-compose run django python manage.py behave --no-input --simple --no-capture concerts/tests/features/

    - name: Stop containers
      run: |
        docker-compose down
